#! /bin/sh

#source "$HOME/.cargo/env"

$HOME/.config/polybar/launch.sh --forest &
setxkbmap -option grp:alt_shift_toggle us,ru &
dunst &
nitrogen --restore &
picom &
sxhkd &

if xrandr -q | grep 'HDMI-1 connected'; then
    xrandr --output HDMI-2 --mode 1920x1080 --left-of eDP-1
    bspc monitor eDP-1 -d I II III IV V
    bspc monitor eHDMI-1 -d VI VII VIII IX X
else
    bspc monitor eDP-1 -d I II III IV V
fi

bspc config border_width        2
bspc config window_gap          3
bspc config top_padding size

bspc config focused_border_color \#528bff
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a polybar border=off manage=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a conky state=lower sticky=on
bspc rule -a xfreerdp state=floating
bspc rule -a neovide desktop=^1
bspc rule -a Thunar desktop=^3

bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true
